services:
  - type: web
    name: resume-kraft
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: STORAGE_PATH
        value: /var/data/resume-kraft/storage
      - key: UPLOAD_FOLDER
        value: /var/data/resume-kraft/uploads
      - key: RESUME_FOLDER
        value: /var/data/resume-kraft/resumes
      - key: PDF_CONVERSION_ENABLED
        value: False